#!/bin/bash

set -eu

function test() {
  local version=$1
  echo "----------------------------------------------------------------------"
  echo "[$version]"
  echo "----------------------------------------------------------------------"
  
  crenv local $version
  crystal spec
}

test 0.33.0
test 1.18.2

